schema_version = "1.0.0"

id = "dimensions"
version = "0.5.0"
name = "Dimensions"
tagline = "Precision dimensions, guides, and measurements"
maintainer = "Cynic Wild"
type = "add-on"
tags = ["3D View"]

blender_version_min = "5.1.0"

license = [
  "SPDX:GPL-3.0-or-later",
]

[build]
paths_exclude_pattern = [
  "__pycache__/",
  "*.py[cod]",
  ".*",
  "*.zip",
]
