DIMENSION_COLLECTION_NAME = "Dimensions"
DIMENSION_OBJECT_PREFIX = "DIM"
SIDEBAR_CATEGORY = "Dimensions"

DEFAULT_EMPTY_DISPLAY_TYPE = "PLAIN_AXES"
DEFAULT_EMPTY_DISPLAY_SIZE = 0.05
DEFAULT_OFFSET_DISTANCE = 0.25
DEFAULT_PRECISION = 3
DEFAULT_LINE_WIDTH = 2.0
DEFAULT_TEXT_SIZE = 14
DEFAULT_ARROW_SIZE = 10.0
DEFAULT_SNAP_PIXEL_THRESHOLD = 18.0
DEFAULT_HOVER_MARKER_SIZE = 8.0
DEFAULT_SELECTION_PIXEL_THRESHOLD = 12.0
