DIMENSION_COLLECTION_NAME = "CAD Dimensions"
DIMENSION_OBJECT_PREFIX = "DIM"
SIDEBAR_CATEGORY = "CAD Dim"

DEFAULT_EMPTY_DISPLAY_TYPE = "PLAIN_AXES"
DEFAULT_EMPTY_DISPLAY_SIZE = 0.05
DEFAULT_OFFSET_PIXELS = 35.0
DEFAULT_PRECISION = 3
